#!bin/bash
#
# kasuatajte lisamise skript
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 failinimi"
else
   failinimi=$1
  if [ -f $failinimi -a -r $failinimi ]; then
    echo "fail on korras"
    for nimi in $(cat $failinimi)
    do
      # faili sisu nähtav, echo asemel kutsuda vajalik skript
      # echo $rida
      sh lisa_kasutaja $nimi # sellega pannakse lisa_kasutaja skript tööle
     done
    else
      echo "probleem failiga $failinimi"
    fi
# kontrolli lõpp
fi
