#!bin/bash
#
# kasutaja public kausta lisamise skript
# kasutaja nimi anda skripti parameetrina
if [ $# -ne 1 ]; then
	echo "kasutusjuhend: $0 kasutajanimi"
else
	# vajaliku muutuja kasutajanime salvestamiseks definitsioon
	kasutajanimi$1
# lisame vajaliku kataloogi
# määrame õigused
## pikk rida
	mkdir /home/$kasutajanimi/public && chown -R $kasutajanimi:$kasutajanimi /home/$kasutajanimi/public && chmod 751 /home/$kasutajanimi/public
## pika rea lõpp
#
# kontroll
if [ $? -eq 0 ]; then
	echo "kasutaja nimega $kasutajanimi kodukaust public loodud"
	cat /etc/passwd | grep $kasutajanimi
	ls -la /home/$kasutajanimi
else
	echo "probleem kasutaja $kasutajanimi lisamisega"
	echo "probleemi kood on $?"
fi
# skripti õige kasutamise kontrolli lõpp
fi
